# Introduccion a numpy

In [1]:
import numpy as np


# Arrays
Es una estructura de Datos
un axis  (esto crresponde al conjunto de ceros)
un shape (3,5) (forma del conjunto de ceros)
un size 15 ( el el total del conjunto de ceros)

In [3]:
# Array cuyos valores son todo 0
a=np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Describe el array
2 axis  

In [4]:
#ejemplo 2
a=np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
